server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml     # mybatis配置文件所在的路径
  type-aliases-package: com.lsy.popj                    # 所有实体类所在的包
  mapper-locations: classpath:mybatis/mapper/**/*.xml   # mapper映射文件

spring:
  application:
    name: springcloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource           # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver          # mysql驱动包
    url: jdbc:mysql://localhost:3306/cloudDB01?useUnicode=true&characterEncoding=utf-8&relaxAutoCommit=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                          # 数据库连接池最小维持连接数
      initial-size: 5                                     # 初始化连接数
      max-total: 5                                        # 最大连接数
      max-wait-millis: 200                               # 超时

eureka:
  client:    #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/   #eureka配置多个就都写入
  instance:  #更改在eureka中注册的实例名称
    instance-id: springcloud-dept8001
    prefer-ip-address: true    #实例访问路径可以显示IP地址

info:      #实例访问的页面信息配置
  app.name: springcloud
  company.name: www.lsy.com
  build.artifactId: ${ project.artifactId }
  build.version: ${ project.version }